# CLI Secrets (managed in 1Password)
export SVN_PASSWORD='{{ op://Employee/CLI Secrets/SVN_PASSWORD }}'
export SVN_USERNAME='{{ op://Employee/CLI Secrets/SVN_USERNAME }}'
export OPENAI_API_KEY='{{ op://Employee/CLI Secrets/OPENAI_API_KEY }}'
export LINEAR_API_KEY='{{ op://Employee/CLI Secrets/LINEAR_API_KEY }}'
export GEMINI_API_KEY='{{ op://Employee/CLI Secrets/GEMINI_API_KEY }}'
export NOTION_API_KEY='{{ op://Employee/CLI Secrets/NOTION_API_KEY }}'
export SLACK_USER_TOKEN='{{ op://Employee/CLI Secrets/SLACK_USER_TOKEN }}'
export GOOGLE_CLOUD_PROJECT_ID='{{ op://Employee/CLI Secrets/GOOGLE_CLOUD_PROJECT_ID }}'
export MB_API_KEY='{{ op://Employee/CLI Secrets/MB_API_KEY }}'
export DEEPSOURCE_TOKEN='{{ op://Employee/CLI Secrets/DEEPSOURCE_TOKEN }}'
